name: Backend CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: techworkhub_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: techworkhub_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo_mysql

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Generate Key
        run: php artisan key:generate 

      - name: Run Migrations
        run: php artisan migrate --force
      
      - name: Run Tests
        run: php artisan test
  
  docker:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/techworkhub-backend:latest \
          -t ghcr.io/${{ github.repository_owner }}/techworkhub-backend:${{ github.ref_name }} \
          -t ghcr.io/${{ github.repository_owner }}/techworkhub-backend:${{ github.sha }} \
          .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/techworkhub-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/techworkhub-backend:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/techworkhub-backend:${{ github.sha }}